// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

const stringOne = "abcd"
const stringTwo = "abcde"

function findTheDifference(stringOne, stringTwo) {
    const s1 = stringOne.split('');
    const s2 = stringTwo.split('');
    s1.sort((a,b) => a.charCodeAt(0) - b.charCodeAt(0));
    s2.sort((a,b) => a.charCodeAt(0) - b.charCodeAt(0));
    let i=0, j=0;
    while(i< s1.length && j<s2.length) {
        if(s1[i] != s2[j]){
            return s2[j];
        }
        i++; j++;
    }
    if(j<s2.length) {
        return s2[j];
    }
}

console.log(findTheDifference(stringOne, stringTwo));
